### ISSUE TITLE
Investigate Using Git Large File Storage for Models and Data

### ISSUE THREAD

**Issue by jermnelson** [sul-dlss-labs/spoc#14]
Look at using [GLFS](https://docs.github.com/en/github/managing-large-files/versioning-large-files) for large models and datasets.

**Comment by jgreben** [comment]
```
Every account using Git Large File Storage receives 1 GB of free storage and 1 GB a month of free bandwidth. If the bandwidth and storage quotas are not enough, you can choose to purchase an additional quota for Git LFS.
```

@jermnelson is 1GB this going to be enough storage, and if not will we be able to purchase additional storage? I am assuming not, and since we will probably be getting a lot of storage on the Dell AI machine, maybe we should make an assumption about using that as a storage location, and specify some documentation and a configuration that includes pointers to that? Thoughts?

**Comment by jgreben** [comment]
I do see this: https://docs.github.com/en/enterprise-server@2.20/admin/user-management/configuring-git-large-file-storage-for-your-enterprise#configuring-git-large-file-storage-to-use-a-third-party-server

So we can possibly use a different storage location.

**Comment by jermnelson** [comment]
> `Every account using Git Large File Storage receives 1 GB of free storage and 1 GB a month of free bandwidth. If the bandwidth and storage quotas are not enough, you can choose to purchase an additional quota for Git LFS.`
> 
> @jermnelson is 1GB this going to be enough storage, and if not will we be able to purchase additional storage? I am assuming not, and since we will probably be getting a lot of storage on the Dell AI machine, maybe we should make an assumption about using that as a storage location, and specify some documentation and a configuration that includes pointers to that? Thoughts?

I agree that 1 GB is likely insufficient for what we need. For now we can continue to use Google Drive for our storage needs and when the Dell AI machine becomes available we can use that for the storage location if needed. To support the running Streamlit app the AWS EC2 image will have 30GB of storage. 



> I do see this: https://docs.github.com/en/enterprise-server@2.20/admin/user-management/configuring-git-large-file-storage-for-your-enterprise#configuring-git-large-file-storage-to-use-a-third-party-server
> 
> So we can possibly use a different storage location.

I think that link is to Github's Enterprise product and may not be available for our use.

**Comment by jermnelson** [comment]
Closing, thank-you @jgreben for investigating!
