### ISSUE TITLE
Revised colors for entities

### ISSUE THREAD

**Issue by cncoleman** [sul-dlss-labs/spoc#80]
CURRENT: options = {"colors": {"LOCATION": "green", "SPECIES": "pink", "HABITAT": "yellow"}}

to RGB
 options = {"colors": {"LOCATION": "rgb(146,194,225)", "SPECIES": "rgb(248,162,89)", "HABITAT": "rgb(192,181,139)"}}

or named
 options = {"colors": {"LOCATION": "lightsteelblue", "SPECIES": "orange", "HABITAT": "olive"}}

or HEX
 options = {"colors": {"LOCATION": "#92c1e1", "SPECIES": "#f8a359", "HABITAT": "#c0b58b"}}

**Comment by cncoleman** [comment]
@jermnelson I would like to pair with you to add these colors -- and to learn how the project code is organized.

**Comment by jermnelson** [comment]
Closed by #83
